security:
  oauth2:
    client:
      client-id: airts
      client-secret: airts123
      scope: read,write
      auto-approve-scopes: '.*'
facebook:
    client:
      clientId: 1780606632177190
      clientSecret: 55bd1adfef5bb1397ef1e9fae512e6ca
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
spring:
  resources:
    chain:
      enabled: true
