CREATE TABLE `LOGIN_REPORT` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `app_version` varchar(25) DEFAULT NULL,
  `channel` varchar(20) DEFAULT NULL,
  `login` varchar(255) DEFAULT NULL,
  `mac_ap` varchar(50) DEFAULT NULL,
  `mac_address` varchar(17) DEFAULT NULL,
  `operator` varchar(25) DEFAULT NULL,
  `signal_strength` varchar(25) DEFAULT NULL,
  `ssid` varchar(35) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `log_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `download_time` bigint(20) DEFAULT NULL,
  `captive_wispr` text,
  `result_wispr` text,
  `local_ip` varchar(15) DEFAULT NULL,
  `access_point_ip` varchar(15) DEFAULT NULL,
  `device_model` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `flg_dw` int(11) DEFAULT '0',
  `osVersion` varchar(30) DEFAULT NULL,
  `authentication_type` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IX_LOGIN` (`login`),
  KEY `IDX_LOGDATE` (`log_date`),
  KEY `IDX_TEMP` (`login`,`log_date`)
) ENGINE=InnoDB AUTO_INCREMENT=18878 DEFAULT CHARSET=utf8;


CREATE TABLE `ERROR_REPORT` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(255) DEFAULT NULL,
  `mac_address` varchar(17) DEFAULT NULL,
  `mac_ap` varchar(50) DEFAULT NULL,
  `signal_strength` varchar(25) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `app_version` varchar(25) DEFAULT NULL,
  `channel` varchar(20) DEFAULT NULL,
  `ssid` varchar(35) DEFAULT NULL,
  `error_type` varchar(50) NOT NULL,
  `error_message` varchar(255) DEFAULT NULL,
  `captive_wispr` text,
  `result_wispr` text,
  `local_ip` varchar(15) DEFAULT NULL,
  `access_point_ip` varchar(15) DEFAULT NULL,
  `create_date` datetime NOT NULL,
  `event_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `device_model` varchar(50) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `operator` varchar(25) DEFAULT NULL,
  `flg_dw` int(11) DEFAULT '0' COMMENT 'Flag para validar se ja foi exportado para o DW ou nao',
  `osVersion` varchar(30) DEFAULT NULL,
  `authentication_type` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_SGI` (`event_date`,`error_type`,`ssid`,`channel`)
) ENGINE=InnoDB AUTO_INCREMENT=19770 DEFAULT CHARSET=utf8;
